### ISSUE TITLE
example/list_images throws

### ISSUE THREAD

**Issue by jpnurmi** [canonical/lxd.dart#11]
Pass `images` argument to `example/list_images.dart`:
```sh
$ dart run example/list_images.dart images
Unhandled exception:
type 'Null' is not a subtype of type 'SimplestreamDownloadItem' in type cast
#0      LxdClient._getRemoteImages (package:lxd/src/lxd_client.dart:349:42)
#1      LxdClient.getRemoteImages (package:lxd/src/lxd_client.dart:303:21)
<asynchronous suspension>
#2      main (file:///path/to/lxd.dart/example/list_images.dart:51:18)
<asynchronous suspension>
```

`_getRemoteImages()` tries to read the `squashfs`:
https://github.com/canonical/lxd.dart/blob/282af6dba518a3c232206408ddfd290039a80c4f/lib/src/lxd_client.dart#L349

images.linuxcontainers.org returns a lot of entries that don't have `squashfs` but they do have `root.squashfs`, though. For example, Almalinux 8:
```dart
{
  lxd.tar.xz: SimplestreamDownloadItem(combinedDisk1ImgSha256: null, combinedSquashfsSha256: d1b431ee8e70f93fbb39fc892d7db4f9708d17a05116f6a802cf1264745a81f9, ftype: lxd.tar.xz, md5: null, path: images/almalinux/8/amd64/cloud/20220522_23:09/lxd.tar.xz, sha256: b3e50cc000f88b8c4b69260eec75861c70c0bd296c5609751173f886ca58d08f, size: 1328),
  root.tar.xz: SimplestreamDownloadItem(combinedDisk1ImgSha256: null, combinedSquashfsSha256: null, ftype: root.tar.xz, md5: null, path: images/almalinux/8/amd64/cloud/20220522_23:09/rootfs.tar.xz, sha256: 77bd31ba7fdaf1909b6b5ffdc154376faa65eeaefb8fe2d566633266893b4dbf, size: 126779364),
  root.squashfs: SimplestreamDownloadItem(combinedDisk1ImgSha256: null, combinedSquashfsSha256: null, ftype: squashfs, md5: null, path: images/almalinux/8/amd64/cloud/20220522_23:09/rootfs.squashfs, sha256: c9effb0f3944ebb279e2445ce594a436155fda98b6c52b6f0fd9e1ff4ecfcf8f, size: 152211456),
  disk.qcow2: SimplestreamDownloadItem(combinedDisk1ImgSha256: null, combinedSquashfsSha256: null, ftype: disk-kvm.img, md5: null, path: images/almalinux/8/amd64/cloud/20220522_23:09/disk.qcow2, sha256: 878a7206da26444abd8ef9fb46e6d9d547d1ebcabe6e5d1bd854d8f976df12c8, size: 687407104),
  root.20220521_23:08.vcdiff: SimplestreamDownloadItem(combinedDisk1ImgSha256: null, combinedSquashfsSha256: null, ftype: squashfs.vcdiff, md5: null, path: images/almalinux/8/amd64/cloud/20220522_23:09/delta-20220521_23:08.vcdiff, sha256: f7857cadd380972a3a4e54c37c66e2149cacf850c63d7d324719ca7c3acc0d07, size: 3862442)
}
```

**Comment by robert-ancell** [comment]
I don't actually know the correct schema in use by lxd, so the current code has been quite trial and error as to which fields exist.
